%% plotStaticValues
% |plotStaticValues(figurenum, sim, value)| plots the static variable |value|
% from simulation |sim| in
% figure |figurenum|
% |sim| is the simulation (generated by <chloroplastSim.html
% |chloroplastSim|> that contains the simulated values


function plotStaticValues(figurenum,sim, value)


switch value
    
    %% This function clearly needs more work
    % right now it only plots |lumen pH|
    case 'lumenpH'
        lumenprotons=getvar('LumenProtons')
        vartoplot=getLumenpH(lumenprotons)
        figure(figurenum)
        set(gca, 'fontsize', 22)
        plot(sim.timevalues, vartoplot);
        grid off
end



%%Get Variable
    function vartoplot=getvar( varname)
        
        a=strcmp(sim.simparams.varsforsim, varname)
        [foo varidx]=find(a)
        if length(varidx)==0
            error('no such variable')
        end
        vartoplot=sim.simulatedvalues(varidx,:)
    end
end